# vim:ft=ansible:
---

- name: Download Liquid Feedback Core {{lf_core_version}} source code
  get_url:
    url: http://www.public-software-group.org/pub/projects/liquid_feedback/backend/{{ lf_core_version }}/liquid_feedback_core-{{ lf_core_version }}.tar.gz
    dest: /tmp/lf_core.tgz

- name: Unarchive the source code
  unarchive:
    src: /tmp/lf_core.tgz
    dest: "{{ lf_home }}"
    copy: no
    creates: "{{ lf_core_dir }}/core.sql"

# Must install PG dev packages to compile lf_update
- name: Ensure PostgreSQL dev packages are installed
  apt:
    name: "postgresql-server-dev-{{ postgresql_version }}"
    state: present
    update_cache: yes

- name: Ensure lf_update binary is compiled
  shell: make
  args:
    chdir: "{{ lf_core_dir }}"
    creates: "{{ lf_core_dir }}/lf_update"

- name: Ensure PostgreSQL database exists
  postgresql_db:
    name: "{{ lf_pg_db }}"

- name: Ensure PostgreSQL user exists and has permissions on database
  postgresql_user:
    db: "{{ lf_pg_db }}"
    name: "{{ lf_pg_user }}"
    priv: ALL

- name: Ensure initial SQL is loaded
  shell: "psql -U {{ lf_pg_user }} -v ON_ERROR_STOP=1 -f core.sql {{ lf_pg_db }} && touch {{ lf_core_dir }}/sql_loaded"
  args:
    chdir: "{{ lf_core_dir }}"
    creates: "{{ lf_core_dir }}/sql_loaded"

- name: Ensure crontab entry exists for lf_update
  cron:
    name: Update Liquid Feedback DB
    user: postgres
    job: "{{ lf_core_dir }}/lf_update dbname={{ lf_pg_db }}"
    minute: "*/{{ lf_core_update_freq }}"
    state: present

- name: Ensure crontab entry exists for lf_issue_order
  cron:
    name: Update Liquid Feedback Issue Order
    user: postgres
    job: "{{ lf_core_dir }}/lf_issue_order dbname={{ lf_pg_db }}"
    minute: "*/{{ lf_core_update_freq }}"
    state: present

- name: Ensure crontab entry exists for lf_suggestion_order
  cron:
    name: Update Liquid Feedback Suggestion Order
    user: postgres
    job: "{{ lf_core_dir }}/lf_suggestion_order dbname={{ lf_pg_db }}"
    minute: "*/{{ lf_core_update_freq }}"
    state: present
